### ISSUE TITLE
Suggestion: PlaySounds Flag

### ISSUE THREAD

**Issue by RocketManKian** [aromaa/WorldGuardExtraFlagsPlugin#211] opened 2022-04-25 00:50 UTC
Hey there!

All is working on my server, however I'm wondering whether this plugin is still maintained hence no update since 2020, anyways...

I would love the ability for you to use more arguments when using the PlaySounds flag. This would be highly useful as I'd like to add the ability to play the sound as 'music' so players can optionally turn the volume down via the Music slider, rather than Master Volume.

![image](https://user-images.githubusercontent.com/47107486/165004294-5ecc2384-e0a9-40f4-9cfc-61da13c50811.png)

Thanks!

**Comment by aromaa** [comment] 2022-05-04 09:50
Dupe of #104

**Closed by aromaa** 2022-05-04 09:50 UTC
