### ISSUE TITLE
Suggestion: add use-trapdoors and use-doors flags

### ISSUE THREAD

**Issue by Leonardo-Fiori** [aromaa/WorldGuardExtraFlagsPlugin#133] opened 2020-08-05 12:25 UTC
`use-trapdoors `and `use-doors` flags would allow region owners to prevent use of doors or trapdoors without preventing "use" of everything else in general.

`use-button`, `use-lever`, `use-pressure` would be cool too

If you don't like this idea, maybe, this would be a better way of doing it:

`allow-use`: [list of materials]
`deny-use`: [list of materials]

item frames are pretty bugged too right now, even if flags are configured correctly players can't interact very well with them

**Comment by aromaa** [comment] 2020-08-05 12:34
Dupe of #55

**Closed by aromaa** 2020-08-05 12:34 UTC
